apiVersion: mpas.ocm.software/v1alpha1
kind: ProductDeployment
metadata:
  creationTimestamp: null
  name: podinfo-test2
  namespace: mpas-podinfo-application
spec:
  component:
    name: ocm.software/demos/podinfo
    registry:
      url: ghcr.io/mohammad-ammar14
    version: v1.0.0
  pipelines:
  - configuration:
      rules:
        name: config
        version: 1.0.0
    localization:
      name: config
      version: 1.0.0
    name: podinfo
    resource:
      name: manifests
      version: 1.0.0
    targetRole:
      selector:
        matchLabels:
          target.mpas.ocm.software/ingress-enabled: "true"
      type: kubernetes
    validation:
      name: validation
      version: 1.0.0
  serviceAccountName: mpas-podinfo-application
status: {}
