apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentSubscription
metadata:
  name: podinfo-subscription
  namespace: mpas-podinfo-application
spec:
  interval: 30s
  component: ocm.software/demos/podinfo
  semver: ">=v1.0.0"
  source:
    url: ghcr.io/ocm-software-provider
    secretRef:
      name: github-access
  destination:
    url: ghcr.io/mohammad-ammar14
    secretRef:
      name: github-access
  # verify:
  # - name: ocm-signing
  #   publicKey:
  #     secretRef:
  #       name: ocm-signing
